-- Legacy migration placeholder adopted from remote Supabase history.
-- Migration: 20260318180000_attendance_close_flow
-- Purpose: align Prisma metadata; schema is captured by later migrations and drift-fix.
-- no-op
