// Catálogo base de permisos y roles. Mantener sincronizado con módulos CRM/HR.

export const CRM_PERMISSIONS = [
  "CRM:LEADS:READ",
  "CRM:LEADS:WRITE",
  "CRM:DEALS:READ",
  "CRM:DEALS:WRITE",
  "CRM:QUOTES:READ",
  "CRM:QUOTES:WRITE",
  "CRM:QUOTES:PUBLISH",
  "CRM:QUOTES:APPROVE",
  "CRM:PROPOSALS:READ",
  "CRM:PROPOSALS:WRITE",
  "CRM:PROPOSALS:PUBLISH",
  "CRM:FILES:READ",
  "CRM:FILES:WRITE",
  "CRM:SETTINGS:ADMIN",
  "CRM:AUDIT:READ"
] as const;

export const MEMBERSHIP_PERMISSIONS = [
  "MEMBERSHIPS:READ",
  "MEMBERSHIPS:WRITE",
  "MEMBERSHIPS:ADMIN",
  "MEMBERSHIPS:DASHBOARD",
  "MEMBERSHIPS:CONTRACTS:READ",
  "MEMBERSHIPS:CONTRACTS:WRITE",
  "MEMBERSHIPS:PAYMENTS:WRITE",
  "MEMBERSHIPS:PLANS:READ",
  "MEMBERSHIPS:PLANS:WRITE",
  "MEMBERSHIPS:CONFIG:READ",
  "MEMBERSHIPS:CONFIG:WRITE",
  "MEMBERSHIPS:USAGE:READ"
] as const;

export const DIAGNOSTIC_PERMISSIONS = [
  "DIAG:READ",
  "DIAG:WRITE",
  "DIAG:VALIDATE",
  "DIAG:RELEASE",
  "DIAG:RADIOLOGY"
] as const;

export const LABTEST_PERMISSIONS = [
  "LABTEST:READ",
  "LABTEST:WRITE",
  "LABTEST:VALIDATE",
  "LABTEST:RELEASE",
  "LABTEST:SEND",
  "LABTEST:ADMIN"
] as const;

export const HR_PERMISSIONS = [
  "HR:EMPLOYEES:READ",
  "HR:EMPLOYEES:WRITE",
  "HR:EMPLOYEES:STATUS",
  "HR:DOCS:READ",
  "HR:DOCS:UPLOAD",
  "HR:DOCS:RESTRICTED",
  "HR:ATTENDANCE:READ",
  "HR:ATTENDANCE:WRITE",
  "HR:ATTENDANCE:CLOSE",
  "HR:DASHBOARD:READ",
  "HR:PAYROLL:READ",
  "HR:PAYROLL:WRITE",
  "HR:PAYROLL:APPROVE",
  "HR:PAYROLL:PUBLISH",
  "HR:SETTINGS:READ",
  "HR:SETTINGS:WRITE"
] as const;

export const SYSTEM_PERMISSIONS = [
  "USERS:ADMIN",
  "SYSTEM:ADMIN",
  "CONFIG_BRANCH_READ",
  "CONFIG_BRANCH_WRITE",
  "CONFIG_THEME_READ",
  "CONFIG_THEME_WRITE",
  "CONFIG_SAT_READ",
  "CONFIG_SAT_WRITE",
  "CONFIG_EMAIL_READ",
  "CONFIG_EMAIL_WRITE",
  "CONFIG_EMAIL_SANDBOX_READ",
  "CONFIG_API_READ",
  "CONFIG_API_WRITE",
  "CONFIG_BACKUP_READ",
  "CONFIG_BACKUP_WRITE"
] as const;

export const ALL_PERMISSION_KEYS: string[] = [
  ...CRM_PERMISSIONS,
  ...MEMBERSHIP_PERMISSIONS,
  ...DIAGNOSTIC_PERMISSIONS,
  ...LABTEST_PERMISSIONS,
  ...HR_PERMISSIONS,
  ...SYSTEM_PERMISSIONS
];

export const ROLE_PERMISSION_MAP: Record<string, string[]> = {
  SUPER_ADMIN: ALL_PERMISSION_KEYS,
  ADMIN: ALL_PERMISSION_KEYS,
  HR_ADMIN: [
    ...HR_PERMISSIONS,
    ...DIAGNOSTIC_PERMISSIONS,
    ...MEMBERSHIP_PERMISSIONS,
    "USERS:ADMIN"
  ],
  HR_USER: [
    "HR:EMPLOYEES:READ",
    "HR:EMPLOYEES:WRITE",
    "HR:DASHBOARD:READ",
    "HR:DOCS:READ",
    "HR:DOCS:UPLOAD",
    "HR:ATTENDANCE:READ",
    "HR:ATTENDANCE:WRITE",
    "HR:PAYROLL:READ",
    "DIAG:READ",
    "DIAG:WRITE"
  ],
  STAFF: ["HR:EMPLOYEES:READ", "HR:DOCS:READ"],
  VIEWER: ["HR:EMPLOYEES:READ"],
  SUPERVISOR: [
    "CRM:LEADS:READ",
    "CRM:LEADS:WRITE",
    "CRM:DEALS:READ",
    "CRM:DEALS:WRITE",
    "CRM:QUOTES:READ",
    "CRM:QUOTES:WRITE",
    "CRM:QUOTES:PUBLISH",
    "CRM:QUOTES:APPROVE",
    "CRM:PROPOSALS:READ",
    "CRM:PROPOSALS:WRITE",
    "CRM:PROPOSALS:PUBLISH",
    "CRM:FILES:READ",
    "CRM:FILES:WRITE",
    "CRM:SETTINGS:ADMIN",
    "CRM:AUDIT:READ"
  ],
  SALES: [
    "CRM:LEADS:READ",
    "CRM:LEADS:WRITE",
    "CRM:DEALS:READ",
    "CRM:DEALS:WRITE",
    "CRM:QUOTES:READ",
    "CRM:QUOTES:WRITE",
    "CRM:QUOTES:PUBLISH",
    "CRM:PROPOSALS:READ",
    "CRM:PROPOSALS:WRITE",
    "CRM:PROPOSALS:PUBLISH",
    "CRM:FILES:READ",
    "CRM:FILES:WRITE"
  ],
  RECEPTION: ["CRM:LEADS:READ", "CRM:DEALS:READ", "CRM:QUOTES:READ"],
  FINANCE: ["CRM:QUOTES:READ", "CRM:QUOTES:APPROVE"],
  LAB_TECH: ["LABTEST:READ", "LABTEST:WRITE", "LABTEST:VALIDATE"],
  LAB_SUPERVISOR: ["LABTEST:READ", "LABTEST:WRITE", "LABTEST:VALIDATE", "LABTEST:RELEASE", "LABTEST:SEND"],
  LAB_ADMIN: [...LABTEST_PERMISSIONS]
};

export const ROLE_CATALOG = [
  "SUPER_ADMIN",
  "ADMIN",
  "HR_ADMIN",
  "HR_USER",
  "STAFF",
  "VIEWER",
  "LAB_TECH",
  "LAB_SUPERVISOR",
  "LAB_ADMIN"
] as const;

export const ONBOARDING_ASSIGNABLE_ROLES = ["STAFF"] as const;
