export const RECEPCION_CAPABILITIES = [
  "RECEPTION_VIEW",
  "RECEPTION_QUEUE_VIEW",
  "RECEPTION_QUEUE_WRITE",
  "RECEPTION_APPOINTMENTS_VIEW",
  "RECEPTION_APPOINTMENTS_WRITE",
  "RECEPTION_ADMISSIONS_VIEW",
  "RECEPTION_ADMISSIONS_WRITE",
  "RECEPTION_CASHIER_VIEW",
  "RECEPTION_CASHIER_WRITE",
  "RECEPTION_REGISTRATIONS_VIEW",
  "RECEPTION_REGISTRATIONS_WRITE"
] as const;

export type RecepcionCapability = (typeof RECEPCION_CAPABILITIES)[number];

export const RECEPCION_SUGGESTED_ROLES = ["SUPER_ADMIN", "OPS", "TENANT_ADMIN", "RECEPTIONIST", "CASHIER"] as const;

export type RecepcionSuggestedRole = (typeof RECEPCION_SUGGESTED_ROLES)[number];

export const RECEPCION_ROLE_LABELS: Record<RecepcionSuggestedRole, string> = {
  SUPER_ADMIN: "Super Admin",
  OPS: "Operaciones",
  TENANT_ADMIN: "Tenant Admin",
  RECEPTIONIST: "Recepcionista",
  CASHIER: "Cajero"
};

export const RECEPCION_CAPABILITY_LABELS: Record<RecepcionCapability, string> = {
  RECEPTION_VIEW: "Ver módulo de Recepción",
  RECEPTION_QUEUE_VIEW: "Ver cola / sala de espera",
  RECEPTION_QUEUE_WRITE: "Gestionar cola / sala de espera",
  RECEPTION_APPOINTMENTS_VIEW: "Ver agenda de citas",
  RECEPTION_APPOINTMENTS_WRITE: "Gestionar agenda de citas",
  RECEPTION_ADMISSIONS_VIEW: "Ver admisiones",
  RECEPTION_ADMISSIONS_WRITE: "Gestionar admisiones",
  RECEPTION_CASHIER_VIEW: "Ver caja rápida",
  RECEPTION_CASHIER_WRITE: "Registrar pagos en caja rápida",
  RECEPTION_REGISTRATIONS_VIEW: "Ver registros pendientes",
  RECEPTION_REGISTRATIONS_WRITE: "Gestionar registros pendientes"
};

export const RECEPCION_CAPABILITIES_BY_ROLE: Record<RecepcionSuggestedRole, RecepcionCapability[]> = {
  SUPER_ADMIN: [...RECEPCION_CAPABILITIES],
  OPS: [
    "RECEPTION_VIEW",
    "RECEPTION_QUEUE_VIEW",
    "RECEPTION_QUEUE_WRITE",
    "RECEPTION_APPOINTMENTS_VIEW",
    "RECEPTION_APPOINTMENTS_WRITE",
    "RECEPTION_ADMISSIONS_VIEW",
    "RECEPTION_ADMISSIONS_WRITE",
    "RECEPTION_CASHIER_VIEW",
    "RECEPTION_REGISTRATIONS_VIEW"
  ],
  TENANT_ADMIN: [...RECEPCION_CAPABILITIES],
  RECEPTIONIST: [
    "RECEPTION_VIEW",
    "RECEPTION_QUEUE_VIEW",
    "RECEPTION_QUEUE_WRITE",
    "RECEPTION_APPOINTMENTS_VIEW",
    "RECEPTION_APPOINTMENTS_WRITE",
    "RECEPTION_ADMISSIONS_VIEW",
    "RECEPTION_ADMISSIONS_WRITE",
    "RECEPTION_CASHIER_VIEW",
    "RECEPTION_REGISTRATIONS_VIEW"
  ],
  CASHIER: [
    "RECEPTION_VIEW",
    "RECEPTION_CASHIER_VIEW",
    "RECEPTION_CASHIER_WRITE",
    "RECEPTION_ADMISSIONS_VIEW",
    "RECEPTION_REGISTRATIONS_VIEW"
  ]
};
