-- Legacy migration placeholder adopted from remote Supabase history.
-- Migration: 20260318120000_hr_onboarding
-- Purpose: align Prisma metadata; schema is captured by later migrations and drift-fix.
-- no-op
