-- Legacy migration placeholder adopted from remote Supabase history.
-- Migration: 20260312120000_attendance_biometric
-- Purpose: align Prisma metadata; schema is captured by later migrations and drift-fix.
-- no-op
